###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: book-store-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: book-store-mailhog
      ports:
        - "${DEV_MAILHOG_PORT:-8081}:8025"

    redis:
      image: redis:alpine
      container_name: book-store-redis

    mysql:
      image: mysql:8.0
      container_name: book-store-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=book_library
        - MYSQL_USER=book
        - MYSQL_PASSWORD=book
      ports:
        - "${DEV_DB_PORT:-8082}:3306"

    webserver:
      image: nginx:alpine
      container_name: book-store-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${DEV_WEB_PORT:-8080}:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: book-store-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    encore:
      image: node:10-alpine
      working_dir: /application
      command: ["yarn", "dev-server", "--host=0.0.0.0"]
      volumes:
        - .:/application
      ports:
        - "${DEV_SERVER_PORT:-8083}:8080"
